# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'tty-platform'
gem "tty-command"
gem "tty-progressbar"
gem "tty-spinner"
gem "pry"

gem "pastel"
gem "rugged"

gem 'faraday'
gem 'faraday-follow_redirects'
gem 'rubyzip'