name: Build and publish Debian package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y ruby-dev build-essential rpm
          sudo gem install fpm

      - name: Build package
        run: |
          fpm -s gem -t deb erhu.gemspec

      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: erhu.deb
          path: ./erhu_0.1.10_all.deb
